Cart and wishlist
MuskanChhatrasal/wow-shop-react pull request #4
Opened 2022-03-29 17:14 UTC by MuskanChhatrasal

2022-03-29 17:26 UTC, Aayushjain-code approved these changes
Nice folder structure.
Different contexts for cart, wishList, and Auth.
Nice UI try to decrease the use of !important in css

2022-03-29 17:26 UTC, Aayushjain-code commented on src/Components/Cart/cart.css
> +  padding: 20px;
use rem instead of px

2022-03-29 17:26 UTC, Aayushjain-code commented on src/Components/Cart/cart.js
> +
try to format the files as too much extra space is there

2022-03-29 17:26 UTC, Aayushjain-code commented on src/Context/AuthContext/authContext.js
> +// export const authReducer = (state, action) => {
you can remove the commented code

2022-03-29 17:26 UTC, Aayushjain-code commented on src/Context/AuthContext/authContext.js
> +		console.log('hello')
you can remove the console.log if its need is over

2022-03-30 16:41 UTC, Developers-codz requested changes
Everything else looks good to me. Also in the categories section view all button is not in center

2022-03-30 16:41 UTC, Developers-codz commented on src/Components/Authentication/signup.js
> +    //  const passwordValidation = /^(?=.\d)(?=.[a-z]).{5,}$/;
appreciation - that you are validating your password

2022-03-30 16:41 UTC, Developers-codz commented on src/Components/Cart/CartSummary.js
> +    <div className="filters summary" style={{marginRight: '2rem'}}>
can avoid inline css

2022-03-30 16:41 UTC, Developers-codz commented on src/Components/Cart/cart.css
> +  width: 20rem !important;
must avoid important as it will rewrite user stylesheets

2022-03-30 16:41 UTC, Developers-codz commented on src/Components/Navbar/navbar.js
> +          <span style={{position: 'absolute', marginTop: '4rem', marginLeft: '-4rem', fontSize: '1.25rem'}} onClick={()=>logout()} className='logout-txt'>logout</span>
remove inline css here as well

2022-03-30 16:41 UTC, Developers-codz commented on src/Components/Wishlist/wishlist.js
> +    {wishlist.map((item)=>{
can destructure items here so that you don't need to write it  multiple times
`{wishlist.map(({name,price,qty,etc})`

2022-03-30 16:41 UTC, Developers-codz commented on src/Context/AuthContext/authReducer.js
> +	}
Take care of indentation you can download `prettier`  extension in vs code

2022-04-07 10:27 UTC, merged